
<h1>Frequently asked questions</h1>
<p>intro</p>

<h2>Beginner, Intermediate, Advanced and Elite?</h2>
<p>The difficulty listed for each exercise is a rough estimate as to what level of fitness is required to perform them. 
There are no universal standards for evaluating the difficulty of bodyweight exercises in the way that happens in some sports like powerlifting where your skill level can be based on weight of your body and lifts.
So for this list we borrow from gymnastics, a sport from which calisthenics borrows. And so the difficulties on this website are in part based on the levels of difficulty defined in the Code of Points of the Federation International of Gymnastics (FIG).</p>
<h3>Beginner</h3>
<p>If you are still improving after every workout or every week then you are beginner. At this level the type of workout you do doesn't matter so much as the fact that you are regularly doing it.
    You might not be able to do all exercises that are labeled for this level yet, but barring health problems or injury you will be able to achieve them in a matter of months or even weeks.</p>
<h3>Intermediate</h3>
<p>At this level sit exercises that most people will have to work to achieve. Though people that are regularly active will have an easier time and may be able to perform some exercise right of the bat.
At this level your workout routine may no longer yield the same amount of improvement as before. 
The routine may need to be adjusted perhaps by adding volume or using a variety of exercise on the same muscles or by making the routine more goal specific e.g. strength focused, hypertrophy focused, etc.
</p>
<h3>Advanced</h3>
<p></p>
<h3>Elite</h3>
<p></p>
