<div class="container" id="tag-container">
    <section id="num">

    <?php
        $firstLetter = "#";
    ?>

    <?php foreach ($this->exercises as $exercise) : ?>

        <?php if( $exercise['name'][0] !== $firstLetter && !ctype_digit($exercise['name'][0]) ): ?>
            <?php $firstLetter =  $exercise['name'][0]; ?>
            <h2>
                <?= $exercise['name'][0]; ?>
            </h2>
        <?php endif; ?>

        <a href="/tag/test/" class="tag"><?= $exercise['name']; ?>
            <?php if(trim($exercise['altNames']) !== ''): ?>
                <span class="count"> (<?= $exercise['altNames']; ?>)
                </span>
            <?php endif; ?>
        </a>

    <?php endforeach; ?>

    </section>
</div>