
<div id="mockup-container">
    <div id="mockup-topbar">topbar</div>
    
    <div id="mockup-content">
        <div id="mockup-content-main">
            <h1 style="display:none;">"The end credits for ..."</h1>
            <blockquote>
                <p>"The end credits for ..."</p>
                <footer>- Jeff, content</footer>
            </blockquote>
            <span></span>
            <br/>
            <div class="thumbs-container">
            <i onclick="myFunction(this)" class="fa fa-thumbs-up"></i>
            <span>200</span>
            </div>
            <progress id="likebar" value="32" max="100"></progress>
            <div class="thumbs-container">
            <i onclick="myFunction(this)" class="fa fa-thumbs-down"></i>
            <span>100</span>
            </div>
            <br />
            <div class="bootstrap-tagsinput">
                <span class="tag label label-info">Amsterdam
                    <span data-role="remove"></span> 
                </span> 
                <span class="tag label label-info">Washington
                    <span data-role="remove"></span>     
                </span> 
                <span class="tag label label-info">Sydney
                    <span data-role="remove"></span>  
                </span> 
                <span class="tag label label-info">Beijing
                    <span data-role="remove"></span>  
                </span> 
                <span class="tag label label-info">Cairo
                    <span data-role="remove"></span> 
                </span> 
            </div>
            <br />
            <dl class="dl-horizontal">
                <dt>...</dt>
                <dd>...</dd>
                <dt>...</dt>
                <dd>...</dd>
            </dl>
            
        </div>
        <div id="mockup-content-side">
            
        </div>
    </div>
    
    <div id="mockup-bottombar">bottombar</div>
</div>