<h1>Progression Chart</h1>

<script>

window.addEventListener('load', (event) => {
    var removeEmptyVariantLists = $('.dropdown-menu.fade-up');
    removeEmptyVariantLists.each(function( index, value ) {
        if($(value).find('div.variant').length === 0){
            $(value).addClass('nodisplayever');
        }
    });
});

</script>

<p>intro</p>
<div id="progressionFilters">
    
    <form method="get" action="<?= $this->url('progress', ['action' => 'progress']) ?>">      
    <fieldset>      
        <legend>Filters:</legend>  
        <?php
        foreach ($this->classifications as $classification) : 
        ?>
            <input type="checkbox" name="classification<?= $classification['id']; ?>" <?= $classification['checked']; ?> value="<?= $classification['id']; ?>"><?= $classification['name']; ?>
        <?php
        endforeach;
        ?>
        <hr>      
         <?php
        foreach ($this->tags as $tag) : 
        ?>
            <input type="checkbox" name="tag<?= $tag['id']; ?>" <?= $tag['checked']; ?> value="<?= $tag['id']; ?>"><?= $tag['name']; ?>
        <?php
        endforeach;
        ?>
        <hr> 
        <input type="submit" value="Submit now" />      
    </fieldset>      
</form>
</div>
<div class="clear"></div>

<div id="progressionContent">
    <?php 
    echo $this->partial('application/index/progressionChartPartial', 
            ['exerciseProgressions'=>$this->exerciseProgressions]); 
    ?>
</div>

<ul class="dropdown-menu fade-up root">
                            <li><a class="dropdown-item">Variants:</a></li>
                            
                <li>
                    <div class="rank1 variant">Vertical Row</div>
                </li>
                
                <li>
                    <div class="rank1 variant">Incline Row</div>
                </li>
                
                        </ul>

    <div class="popover container-drop right in" style="top: 374.5px; left: 424px; display: block;">
        <div class="arrow"></div>
        <div>
            <h3 class="dropdown-title">Variants:</h3>
            <div class="dropdown-content">
                <ul >
                    
                    
                    <li>Vertical Row</li>
                    <li>Incline Row</li>
                </ul>
            </div>
        </div>
    </div>

<div class="clear"></div>
