<h1>Progression Chart</h1>

<style type="text/css">

/* ============ only desktop view ============ */
@media all and (min-width: 992px) {
	.navbar .nav-item .dropdown-menu{  display:block; opacity: 0;  visibility: hidden; transition:.3s; margin-top:0;  }
	.navbar .nav-item:hover .nav-link{ color: #fff;  }
	.navbar .dropdown-menu.fade-down{ top:80%; transform: rotateX(-75deg); transform-origin: 0% 0%; }
	.navbar .dropdown-menu.fade-up{ top:180%;  }
	.navbar .nav-item:hover .dropdown-menu{ transition: .3s; opacity:1; visibility:visible; top:100%; transform: rotateX(0deg); }
}	
/* ============ desktop view .end// ============ */


</style>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
 
 <ul class="navbar-nav">

	<li class="nav-item dropdown">
	    <a class="nav-link  dropdown-toggle" href="#" data-toggle="dropdown">  Hover up  </a>
	    <ul class="dropdown-menu fade-up">
		  <li><a class="dropdown-item" href="#"> Submenu item 1</a></li>
		  <li><a class="dropdown-item" href="#"> Submenu item 2 </a></li>
		  <li><a class="dropdown-item" href="#"> Submenu item 3 </a></li>
	    </ul>
	</li>
</ul>


</nav>
<p>intro</p>
<div id="progressionFilters">
    
    <form method="get" action="<?= $this->url('progress', ['action' => 'progress']) ?>">      
    <fieldset>      
        <legend>Filters:</legend>  
        <?php
        foreach ($this->classifications as $classification) : 
        ?>
            <input type="checkbox" name="classification<?= $classification['id']; ?>" <?= $classification['checked']; ?> value="<?= $classification['id']; ?>"><?= $classification['name']; ?>
        <?php
        endforeach;
        ?>
        <hr>      
         <?php
        foreach ($this->tags as $tag) : 
        ?>
            <input type="checkbox" name="tag<?= $tag['id']; ?>" <?= $tag['checked']; ?> value="<?= $tag['id']; ?>"><?= $tag['name']; ?>
        <?php
        endforeach;
        ?>
        <hr> 
        <input type="checkbox" name="variation" <?= $this->showVariation ?> value="False">Show variation<br/><br/> 
        <input type="submit" value="Submit now" />      
    </fieldset>      
</form>
</div>
<div class="clear"></div>
    
<div id="progressionContent">
    <ul class="tree">
        <?php
        
        // todo: make variations only show when clicking parent, instead of showing as child
        // show classification blocks; use tabs
             
        // hover event: https://stackoverflow.com/questions/41196530/wrap-image-with-div-on-hover-using-jquery
             
        $parent_ids = array();
        $parent_parent_id = null; //the parent_id of an items parent              
        $totalOutput = "";

        foreach ($this->exerciseProgressions as $exerciseProgressions) : 
            if($exerciseProgressions->exercise_parent_id == NULL){
                array_push($parent_ids, $exerciseProgressions->id);
                $totalOutput .= "
                    <li>
                        <span class='rank$exerciseProgressions->difficulty'>".$exerciseProgressions->name."</span>
                        <ul class='dropdown-menu fade-up'>
                            <li><a class='dropdown-item' >Variants:</a></li>
                            <li>
                                <span class='rank1'>Vertical Row</span>                    
                            </li>
                            <li>
                                <span class='rank1'>Incline Row</span>
                            </li>
                        </ul>
                        {child".$exerciseProgressions->id."}
                    </li>
                    ";
            } 
            // Is child
            else if(in_array($exerciseProgressions->exercise_parent_id, $parent_ids)){        
                array_push($parent_ids, $exerciseProgressions->id);
       
                $parent_parent_id = $exerciseProgressions->exercise_parent_id;
                
                if (($key = array_search($parent_parent_id, $parent_ids)) !== false) {
                   // unset($messages[$key]);
                     unset($parent_ids[$key]); 
                }

                $output = "
                    <ul>
                        <li class='{only".$exerciseProgressions->exercise_parent_id."}'>
                            <span class='rank$exerciseProgressions->difficulty'>".$exerciseProgressions->name."</span>
                            {child".$exerciseProgressions->id."}
                        </li>
                        {sibling".$exerciseProgressions->exercise_parent_id."}
                    </ul>";

                $totalOutput = str_replace(
                    "{child".$exerciseProgressions->exercise_parent_id."}", 
                    $output, 
                    $totalOutput
                );
            } 
            // Is sibling
            else if($exerciseProgressions->exercise_parent_id == $parent_parent_id) {
                array_push($parent_ids, $exerciseProgressions->id);

                $output = "
                    <li>
                        <span class='rank$exerciseProgressions->difficulty'>".$exerciseProgressions->name."</span>
                        {child".$exerciseProgressions->id."}
                    </li>
                    {sibling".$exerciseProgressions->exercise_parent_id."}";

                $totalOutput = str_replace(
                    "{sibling".$exerciseProgressions->exercise_parent_id."}", 
                    $output, 
                    $totalOutput
                );     

                $totalOutput = str_replace(
                    "{only".$exerciseProgressions->exercise_parent_id."}", 
                    "", 
                    $totalOutput
                );
            } else {
               // die("should not end up here");
            }

        endforeach;
        for ($i = 1; $i <= 100; $i++) {
            $totalOutput = str_replace(
                "{child".$i."}", 
                "", 
                $totalOutput
            ); 
            $totalOutput = str_replace(
                "{sibling".$i."}", 
                "", 
                $totalOutput
            );  
            $totalOutput = str_replace(
                "{only".$i."}", 
                "only", 
                $totalOutput
            );
        }
        echo $totalOutput;

        ?>
    </ul>
</div>
<div class="clear"></div>
