<?php


//$html = file_get_contents('http://localhost/18laminas/public/index');

if(false)
{
	
	
	
	var_dump(file_get_contents('http://localhost/18laminas/public/index'));
	
}



//*****************cache only if page permits*********************************
    // these lines create a cached filename according to the current route. 

    $url = $_SERVER["REQUEST_URI"];
    $break = Explode('/', $url);
    $file = $break[count($break) - 1];
	if( $break[count($break) - 1] != "public" && $break[count($break) - 2] != "public")
	{
		$file .= "-".$break[count($break) - 2];
		if( $break[count($break) - 3] != "public")
		{
			$file .= "-".$break[count($break) - 3];
			if( $break[count($break) - 4] != "public")
			{
				$file .= "-".$break[count($break) - 3];
			}
		}
	}
    echo "file = ".$file . "<br/>";
    $cachefile = $this->basePath('cache/'.'cached-'.$file.'.html');
	echo $cachefile;
    //life of cache file in years + weeks + days + hours + minutes
    $cachetime = (0 * 31449600) + (0 * 604800) + (0 * 86400) + (0 * 3600) + (0 * 60);
    // Serve from the cache if it is younger than $cachetime
    if (file_exists('./' . $cachefile) && time() - $cachetime < filemtime($cachefile)) {
        echo "<!-- Cached copy, generated ".date('H:i', filemtime($cachefile))." -->\n";
        include($cachefile);
        exit;
    }else{
        echo "<!-- Cache not found -->\n";
    }

    ob_start(); // Start buffering output
//*****************************************************************************
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('FitnessPlan for Clever Progress')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/tabs.css'))
        ?>
        
        <!-- Scripts -->
        <?= $this->headScript()->appendFile($this->basePath().'/js/jquery-3.5.1.min.js'); ?>
        <?= $this->headScript()->appendFile($this->basePath().'/js/cbpFWTabs.js'); ?>

        
    </head>
    <body>
        <svg height="0" width="0" style="position: absolute; margin-left: -100%;"> 
            <defs>
                <g id="shape-logo">
                    <line x1="0" y1="50" x2="150" y2="50" stroke-width="4" />
                    <path d="M 25 50 q 50 -50 100 0" stroke-width="5" fill="none" />
                    <line x1="35" y1="15" x2="50" y2="30" stroke-width="4" />
                    <line x1="75" y1="4" x2="75" y2="25" stroke-width="4" />
                    <line x1="115" y1="15" x2="100" y2="30" stroke-width="4" />
                </g>
            </defs>
        </svg>
        <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>" style="width:150px;">
                        <svg style="stroke: white;height:55px;width:150px;display:inline-block;float:left;"> 
                                <use xlink:href='#shape-logo'></use>
                                <title>title</title>
                        </svg>
                        <span style="display:inline-block;float:left;margin-left:27px;">FitnessPlan</span>
                    </a>
                </div>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <?= $this->navigation('navigation')
                        ->menu()
                        ->setMinDepth(0)
                        ->setMaxDepth(0)
                        ->setUlClass('nav navbar-nav') ?>
                    <!--ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="<?= $this->url('home') ?>">Home <span class="sr-only">(current)</span></a>
                        </li>
                    </ul-->
                </div>
                <div class="input-group md-form form-sm form-2 pl-0" style="flex-basis:200px; display:none;">
                    <input class="form-control my-0 py-1" type="text" placeholder="Search" aria-label="Search">
                    <div class="input-group-append">
                      <span class="input-group-text lighten-3" id="basic-text1"><i class="fas fa-search text-grey"
                          aria-hidden="true"></i></span>
                    </div>
                  </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <!--footer>
                <p>&copy; <?= date('Y') ?> <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.</p>
            </footer-->
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
    </body>
</html>

<?php 
//******************check for cache filename*****************

if($cachefile != null){
    echo "<br/>here";
    echo $this->basePath();
    echo "<br/>";
    echo $cachefile;
    echo "<br/>";
    echo $_SERVER['DOCUMENT_ROOT'];
    // Cache the contents to a file
    $cached = fopen($_SERVER['DOCUMENT_ROOT'].$cachefile, 'w');
    fwrite($cached, ob_get_contents());
    fclose($cached);
    
    ob_end_flush(); // Send the output to the browser
}
//**********************************************************


/*
for($i = 1; $i < 96; $i++){
    $urlFinal = '0';
    if($i < 10){
        $url1 = 'http://jb2448.info/_data/i/galleries/How_I_Became_a_Pokemon_Card/RAWs/Volume_2/PCNNW_V2_00';
        $url2 = '-me.jpg';
        $urlFinal = $url1 . $i . $url2;
    } else {
        $url1 = 'http://jb2448.info/_data/i/galleries/How_I_Became_a_Pokemon_Card/RAWs/Volume_2/PCNNW_V2_0';
        $url2 = '-me.jpg';
        $urlFinal = $url1 . $i . $url2;
        
    }
    //get img and save it
    $url = $urlFinal;
    $img = './How_I_Became_A_Pokemon_Card/RAWs/volume_2/page '.$i.'.jpg';
    file_put_contents($img, file_get_contents($url));
}*/


?>
