<script type="text/javascript">

$(document).ready(function() { 
    var example = $( "#examples" ).not(".disabled-button");
    var reading = $( "#readings" ).not(".disabled-button");
    var examplescontent = $( "#examplescontent" );
    var readingscontent = $( "#readingscontent" );

    if(example.length > 0)
    {
        example.click(function() {
            examplescontent.removeClass("nodisplay");
            readingscontent.addClass("nodisplay");
        });
    }
    if(reading.length > 0)
    {
        reading.click(function() {
            examplescontent.addClass("nodisplay");
            readingscontent.removeClass("nodisplay");
        });
    }
});

</script>
<?php
$difficultyrankingdetail_array  = array(1 => 'Beginner', 2 => 'Intermediate', 3 => 'Advanced', 4 => 'Elite');

$exampleClass = 'disabled-button';
$readingClass = 'disabled-button';

if($this->exerciseCurrentRow->example !== null && $this->exerciseCurrentRow->example !== '' && $this->exerciseCurrentRow->example !== '<p></p>')
    $exampleClass = '';

if(count($this->exerciseReadings) > 0)
    $readingClass = '';
?>

<h1>
    <?= 
        $this->exerciseCurrentRow->name; 
        $this->headTitle($this->exerciseCurrentRow->name);
    ?>
    <?php if(trim($this->exerciseCurrentRow->altNames) !== ''): ?>
        <small>
        Alternate names: <?= $this->exerciseCurrentRow->altNames; ?>
        </small>
    <?php endif; ?>
</h1>

<div>
    <small>
    Classification: 
    <?php foreach ($this->exerciseClassifications as $exerciseClassifications) : ?>
        <?= $exerciseClassifications['name']; ?>
    <?php endforeach; ?>
    <br/>
    Difficulty: 
    <?= $difficultyrankingdetail_array[$this->exerciseCurrentRow->difficulty]; ?>
    <br/>
    <?php if(count($this->exerciseTags) > 0): ?>
        Tags: 
        <?php foreach ($this->exerciseTags as $key => $exerciseTags) : ?>
            <?= $exerciseTags['name']; 
                end($this->exerciseTags);
                    echo ', ';
            ?>
        <?php endforeach; ?>
    <?php endif; ?>
    </small>
</div>

<div>
    <div class="detail-media">
        <?php if($this->exerciseCurrentRow->media !== null && $this->exerciseCurrentRow->media !== ''): ?>
            <iframe width="560" height="315" src="<?=$this->exerciseCurrentRow->media; ?>" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <?php endif; ?>
    </div>
    <div class="row">
        <!-- use this https://www.w3schools.com/bootstrap/bootstrap_button_groups.asp for these 2 -->
        <div id="examples" class="col-md-6 btn <?= $exampleClass; ?>">
            Examples
        </div>
        <div id="readings" class="col-md-6 btn <?= $readingClass; ?>">
            Readings
        </div>
    </div>
    <div id="examplescontent" class="row">
        <div class="col-md-12">
            <?php foreach ($this->exerciseExamples as $exerciseExamples) : ?>
                <?= $exerciseExamples->example; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div id="readingscontent" class="row nodisplay">
        <?php foreach ($this->exerciseReadings as $exerciseReadings) : ?>
        
        <?php
        $hasDesc = true;
        $hasUrl = true;
        $hasArchive = false;
        
        $col1 = 7;
        $col2 = 2;
        $col3 = 3;
        
        $count = 0;
        
        /*if(!empty($exerciseReadings->desc))
        {
            $hasDesc = true;
            $count++;
        }
        
        if(!empty($exerciseReadings->urlName))
        {
            $hasUrl = true;
            $count++;
        }*/
        
        if(!empty($exerciseReadings->archive))
        {
            $hasArchive = true;
            $count++;
        }
        
        if($hasArchive == false){
            $col1 = 7;
            $col2 = 5;
            $col3 = 0;
        }
        // todo change styling to fit smaller spaces
        ?>
        
            <div class="col-alter col-md-<?= $col1 ?>"><?= $exerciseReadings->desc; ?></div>
            <div class="col-alter col-md-<?= $col2 ?>"><a href="<?= $exerciseReadings->url; ?>">Link</a></div>
            <?php if($hasArchive == true): ?>
                <div class="col-alter col-md-<?= $col3 ?>"><a href="<?= $exerciseReadings->archive; ?>">Archive</a></div>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>
<div class="clear"></div>

<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading pointer" data-toggle="collapse" data-parent="#accordion" data-target="#collapse1">
      <h4 class="panel-title">
        Variations
        <span class="badge floatright"><?= $exerciseVariations->count(); ?></span>
      </h4>
    </div>
    <div id="collapse1" class="panel-collapse collapse">
      <div class="panel-body">
        <?php foreach ($this->exerciseVariations as $exerciseVariations) : ?>
            <a href="<?=$this->url('detail', ['action' => 'detail', 'id' => $exerciseVariations['id']]); ?>">
            <h5><?= $exerciseVariations->name; ?></h5>
            </a>
            <p>
                <?= $exerciseVariations->example; ?>
            </p>
            <hr/>
        <?php endforeach; ?>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading pointer" data-toggle="collapse" data-parent="#accordion" data-target="#collapse2">
      <h4 class="panel-title">
        Progression tree
      </h4>
    </div>
    <div id="collapse2" class="panel-collapse collapse in">
    <div class="panel-body">        
        <?php 
        echo $this->partial('application/index/progressionChartPartial', 
                ['exerciseProgressions'=>$this->exerciseProgressions, 'classifications'=>$this->exerciseClassifications2]); 
        ?>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading pointer" data-toggle="collapse" data-parent="#accordion" data-target="#collapse3">
      <h4 class="panel-title">
        Community discussion Link
      </h4>
    </div>
    <div id="collapse3" class="panel-collapse collapse">
      <div class="panel-body">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit,
        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
        minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
        commodo consequat.
      </div>
    </div>
  </div>
</div>