<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Welcome to FitnessPlan!</h1>

    <p>
        FitnessPlan is for those who want to learn how to exercise using nothing but their own body. 
        Here you'll find not only information on exercises like push-ups and pull-ups but also how to develop to more advanced exercises like the planche and one-arm pull-up. 
    </p>
    <p>
        For a list of all exercise make sure to check out our <a href="<?= $this->url('index', ['action' => 'index']) ?>">exercises wiki</a>
        </p>
    <hr class="my-4" style="display:none;">

    <a class="btn btn-primary btn-lg" href="https://github.com/laminas" target="_blank" style="display:none;">Button &raquo;</a>
</div>

<?php 
$tags = array("<p>", "</p>");
?>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header"><?= $this->exercise1->name ?></h2>
        <div class="card-body">
            <p>
                <?php
                $stripped_content = str_replace($tags, "", $this->exercise1->example);
                echo $stripped_content;
                ?>
            </p>

            <a class="btn btn-primary" href="<?= $this->url('detail', ['action' => 'detail', 'id' => $this->exercise1->id])?>" target="_self">Visit &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header"><?= $this->exercise2->name ?></h2>
        <div class="card-body">
            <p>
                <?php
                $stripped_content = str_replace($tags, "", $this->exercise2->example);
                echo $stripped_content;
                ?>
            </p>

            <a class="btn btn-primary" href="<?= $this->url('detail', ['action' => 'detail', 'id' => $this->exercise1->id])?>" target="_self">Visit &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header"><?= $this->exercise3->name ?></h2>
        <div class="card-body">
            <p>
                <?php
                $stripped_content = str_replace($tags, "", $this->exercise3->example);
                echo $stripped_content;
                ?>
            </p>

            <a class="btn btn-primary" href="<?= $this->url('detail', ['action' => 'detail', 'id' => $this->exercise1->id])?>" target="_self">Visit &raquo;</a>
        </div>
    </div>
</div>
