<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Welcome to<br>Test</h1>

    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed a mauris sagittis, egestas lectus ac, auctor mi. In feugiat mollis tortor et tincidunt. Nulla eget accumsan lacus. Donec rhoncus ornare commodo. Ut et neque nunc. Nunc vitae consequat turpis, vitae ultricies arcu. Pellentesque eu ex ut sapien dignissim hendrerit ut non velit. Curabitur pellentesque eget tellus at vulputate. Vestibulum egestas ligula nec ligula posuere, quis vulputate arcu imperdiet. Duis volutpat, diam in semper tincidunt, sapien velit suscipit diam, pretium posuere nisi leo et est. Integer in efficitur enim. Praesent ullamcorper ante vel neque commodo, id mattis metus pretium.    </p>

    <hr class="my-4">

    <a class="btn btn-primary btn-lg" href="https://github.com/laminas" target="_blank">Button &raquo;</a>
</div>

<div class="card-deck">
    <div class="card">
        <h2 class="card-header"><?= $this->exercise1->name ?></h2>
        <div class="card-body">
            <p>
                <?= $this->exercise1->example ?>
            </p>

            <a class="btn btn-primary" href="<?= $this->url('detail', ['action' => 'detail', 'id' => $this->exercise1->id])?>" target="_self">Visit &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header"><?= $this->exercise2->name ?></h2>
        <div class="card-body">
            <p>
                 <?= $this->exercise2->example ?>
            </p>

            <a class="btn btn-primary" href="<?= $this->url('detail', ['action' => 'detail', 'id' => $this->exercise1->id])?>" target="_self">Visit &raquo;</a>
        </div>
    </div>

    <div class="card">
        <h2 class="card-header"><?= $this->exercise3->name ?></h2>
        <div class="card-body">
            <p>
                 <?= $this->exercise3->example ?>
            </p>

            <a class="btn btn-primary" href="<?= $this->url('detail', ['action' => 'detail', 'id' => $this->exercise1->id])?>" target="_self">Visit &raquo;</a>
        </div>
    </div>
</div>
