<script>
    window.addEventListener('load', (event) => {
        var removeEmptyVariantLists = $('.dropdown-menu.fade-up');
        removeEmptyVariantLists.each(function( index, value ) {
            if($(value).find('div.variant').length === 0){
                $(value).addClass('nodisplayever');
            }
        });
        
        var menuItems = $('.main-navigation li');

        menuItems.on("click", function(event) {

            menuItems.removeClass("active");

            $(this).addClass("active");

            $(".tree-container").css({
                "background": $(this).data("bg-color")
            });

            event.preventDefault();
        });
    });
</script>

<svg height="0" width="0" style="position: absolute; margin-left: -100%;">
  
  <defs>
    
    <filter id='shadow'>
      <feComponentTransfer in="SourceGraphic">
        <feFuncR type="discrete" tableValues="0"/>
        <feFuncG type="discrete" tableValues="0"/>
        <feFuncB type="discrete" tableValues="0"/>
      </feComponentTransfer>
      <feGaussianBlur stdDeviation="1"/>
       <feComponentTransfer><feFuncA type="linear" slope="0.2"/></feComponentTransfer>
      <feOffset dx="5" dy="1" result="shadow"/>
      <feComposite in="SourceGraphic" />
    </filter>
        
    <linearGradient id="tab-1-bg" x1="0%" y1="0%" x2="0%" y2="65%">
      <stop offset="0%" style="stop-color: rgba(136, 195, 229, 1.0);" />
      <stop offset="100%" style="stop-color: rgba(118, 160, 192, 1.0);" />
    </linearGradient>
    
    <linearGradient id="tab-2-bg" x1="0%" y1="0%" x2="0%" y2="65%">
      <stop offset="0%" style="stop-color: rgba(149, 190, 233, 1.0);" />
      <stop offset="100%" style="stop-color: rgba(112, 153, 213, 1.0);" />
    </linearGradient>
    
    <linearGradient id="tab-3-bg" x1="0%" y1="0%" x2="0%" y2="65%">
      <stop offset="0%" style="stop-color: rgba(61, 149, 218, 1.0);" />
      <stop offset="100%" style="stop-color: rgba(43, 130, 197, 1.0);" />
    </linearGradient>
    
    <linearGradient id="tab-4-bg" x1="0%" y1="0%" x2="0%" y2="65%">
      <stop offset="0%" style="stop-color: rgba(72, 204, 243, 1.0);" />
      <stop offset="100%" style="stop-color: rgba(71, 194, 243, 1.0);" />
    </linearGradient>
    
  </defs>
  
  <path id="tab-shape" class="tab-shape" d="M116.486,29.036c-23.582-8-14.821-29-42.018-29h-62.4C5.441,0.036,0,5.376,0,12.003v28.033h122v-11H116.486
			z">
  
</svg>

<nav role="navigation" class="main-navigation">
  <ul>
    <li class="tab-1 active" data-bg-color="rgba(118, 160, 192, 1.0)">
      <a href="#home">
        <span>Home</span>
        <svg viewBox="0 0 122 40">
           <use xlink:href="#tab-shape"></use>
        </svg>
      </a>
    </li>
    <li class="tab-2" data-bg-color="rgba(112, 153, 213, 1.0)">
      <a href="#about">
        <span>About</span>
        <svg viewBox="0 0 122 40">
          <use xlink:href="#tab-shape"></use>
        </svg>
      </a>
    </li>
    <li class="tab-3" data-bg-color="rgba(43, 130, 197, 1.0)">
      <a href="#clients">
        <span>Clients</span>
        <svg viewBox="0 0 122 40">
          <use xlink:href="#tab-shape"></use>
        </svg>
      </a>
    </li>
    <li class="tab-4" data-bg-color="rgba(71, 194, 243, 1.0)">
      <a href="#contact">
        <span>Contact</span>
        <svg viewBox="0 0 122 40">
          <use xlink:href="#tab-shape"></use>
        </svg>
      </a>
    </li>
  </ul>
</nav>




<div class="tree-container">
<ul class="tree">
    
    <?php
    $difficultyranking_array  = array(1 => 'Beginner', 2 => 'Intermediate', 3 => 'Advanced', 4 => 'Elite');

    // todo: make variations only show when clicking parent, instead of showing as child
    // show classification blocks; use tab pages?

    // hover event: https://stackoverflow.com/questions/41196530/wrap-image-with-div-on-hover-using-jquery
    // show small icon that exercise has variations
    // show small icon for categories e.g. push-up icon, sit-up, squat, pull-up
    // change hover popup to right with arrow e.g. srs

    $parent_ids = array();
    $parent_parent_id = null; //the parent_id of an items parent              
    $totalOutput = "";
    $currentClassification = 0;

    foreach ($this->exerciseProgressions as $exerciseProgressions) : 
        if($exerciseProgressions->exercise_parent_id == NULL){
            array_push($parent_ids, $exerciseProgressions->id);
            if($currentClassification != $exerciseProgressions->classifications_id) {
                $totalOutput .= "<hr/>";
                $currentClassification = $exerciseProgressions->classifications_id;
            }
            
            
            $totalOutput .= "
                <li>
                    <a href='".$this->url('detail', ['action' => 'detail', 'id' => $exerciseProgressions['id']])."' class='rank$exerciseProgressions->difficulty primary'>
                        <div class='text-rank'>".
                            $difficultyranking_array[$exerciseProgressions->difficulty]."
                        </div>".
                        $exerciseProgressions->name."
                        <ul class='dropdown-menu fade-up root'>
                            <li>Variants:</li>
                            {variant".$exerciseProgressions->id."}
                        </ul>
                    </a>
                    {child".$exerciseProgressions->id."}
                </li>
                ";
        } 
        // Is variation
        else if($exerciseProgressions->isVariation){
            $output = "
                <li>
                    <div class='rank$exerciseProgressions->difficulty variant'>".$exerciseProgressions->name."</div>
                </li>
                {variant".$exerciseProgressions->exercise_parent_id."}";

            $totalOutput = str_replace(
                "{variant".$exerciseProgressions->exercise_parent_id."}", 
                $output, 
                $totalOutput
            );
        }
        // Is child
        else if(in_array($exerciseProgressions->exercise_parent_id, $parent_ids)){        
            array_push($parent_ids, $exerciseProgressions->id);

            $parent_parent_id = $exerciseProgressions->exercise_parent_id;

            if (($key = array_search($parent_parent_id, $parent_ids)) !== false) {
                 unset($parent_ids[$key]); 
            }

            $output = "
                <ul>
                    <li class='{only".$exerciseProgressions->exercise_parent_id."}'>
                        <a href='".$this->url('detail', ['action' => 'detail', 'id' => $exerciseProgressions['id']])."' class='rank$exerciseProgressions->difficulty primary'>
                            <div class='text-rank'>".
                                $difficultyranking_array[$exerciseProgressions->difficulty]."
                            </div>".
                            $exerciseProgressions->name."
                            <ul class='dropdown-menu fade-up'>
                                <li>Variants:</li>
                                {variant".$exerciseProgressions->id."}
                            </ul>
                        </a>
                        {child".$exerciseProgressions->id."}
                    </li>
                    {sibling".$exerciseProgressions->exercise_parent_id."}
                </ul>";

            $totalOutput = str_replace(
                "{child".$exerciseProgressions->exercise_parent_id."}", 
                $output, 
                $totalOutput
            );
        } 
        // Is sibling
        else if($exerciseProgressions->exercise_parent_id == $parent_parent_id) {
            array_push($parent_ids, $exerciseProgressions->id);

            $output = "
                <li>
                    <a href='".$this->url('detail', ['action' => 'detail', 'id' => $exerciseProgressions['id']])."' class='rank$exerciseProgressions->difficulty sibling'>
                        <div class='text-rank'>".
                            $difficultyranking_array[$exerciseProgressions->difficulty]."
                        </div>".
                        $exerciseProgressions->name."
                        <ul class='dropdown-menu fade-up'>
                            <li>Variants:</li>
                            {variant".$exerciseProgressions->id."}
                        </ul>
                    </a>
                    {child".$exerciseProgressions->id."}
                </li>
                {sibling".$exerciseProgressions->exercise_parent_id."}";

            $totalOutput = str_replace(
                "{sibling".$exerciseProgressions->exercise_parent_id."}", 
                $output, 
                $totalOutput
            );     

            $totalOutput = str_replace(
                "{only".$exerciseProgressions->exercise_parent_id."}", 
                "", 
                $totalOutput
            );
        } else {
           // die("should not end up here");
        }

    endforeach;
    for ($i = 1; $i <= 200; $i++) {
        $totalOutput = str_replace(
            "{child".$i."}", 
            "", 
            $totalOutput
        ); 
        $totalOutput = str_replace(
            "{sibling".$i."}", 
            "", 
            $totalOutput
        );  
        $totalOutput = str_replace(
            "{variant".$i."}", 
            "", 
            $totalOutput
        );  
        $totalOutput = str_replace(
            "{only".$i."}", 
            "only", 
            $totalOutput
        );
    }
    echo $totalOutput;

    ?>
</ul>
    </div>